# Generated by Django 4.0.6 on 2023-10-20 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodtype',
            name='category',
            field=models.CharField(choices=[('drinks', 'Drinks'), ('gurasa', 'Gurasa'), ('meat', 'Meats'), ('pizza', 'Pizza')], max_length=15),
        ),
    ]
