# Generated by Django 4.0.6 on 2023-10-26 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerreview',
            name='image',
        ),
    ]
