# Generated by Django 4.0.6 on 2023-10-20 10:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerreview',
            old_name='post',
            new_name='comment',
        ),
        migrations.RenameField(
            model_name='customerreview',
            old_name='title',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='customerreview',
            name='description',
        ),
        migrations.AddField(
            model_name='customerreview',
            name='rate',
            field=models.IntegerField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
