# Generated by Django 4.0.6 on 2023-10-26 22:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_remove_customerreview_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerreview',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='static/review-images'),
            preserve_default=False,
        ),
    ]
