# Generated by Django 4.0.6 on 2023-10-26 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0003_customerreview_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerreview',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/review-images'),
        ),
    ]
